# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

# Copy all source files
COPY . .

# Build the TypeScript project
RUN npm run build

# Remove dev dependencies for production
RUN npm prune --production

# Start the MCP server
CMD ["node", "dist/index.js"]
